export const BASE_URL=`https://movienew.cybersoft.edu.vn`;
export const tokenCybersoft=`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5Mb3AiOiJCb290Y2FtcCBETjEwIiwiSGV0SGFuU3RyaW5nIjoiMjIvMDgvMjAyNCIsIkhldEhhblRpbWUiOiIxNzI0Mjg0ODAwMDAwIiwibmJmIjoxNjkzMTU1NjAwLCJleHAiOjE3MjQ0MzI0MDB9.JjDqstSevsNiLhXlkGx2wJPz6otbfBWxfaCHMzBpb6s`;
export const ACCESS_TOKEN = "access_token";